mkdir -p ./DIR_var_db
mkdir -p ./DIR_var_db/sudo
mkdir -p ./DIR_var_db/iscsi
mkdir -p ./DIR_var_db/pkg
mkdir -p ./DIR_var_account
mkdir -p ./DIR_var_amavis
mkdir -p ./DIR_var_amavis/db
mkdir -p ./DIR_var_amavis/quarantine
mkdir -p ./DIR_var_amavis/tmp
mkdir -p ./DIR_var_amavis/var
mkdir -p ./DIR_var_imap
mkdir -p ./DIR_var_imap/db
mkdir -p ./DIR_var_imap/proc
mkdir -p ./DIR_var_imap/quota
mkdir -p ./DIR_var_imap/quota/z
mkdir -p ./DIR_var_imap/quota/q
mkdir -p ./DIR_var_imap/quota/x
mkdir -p ./DIR_var_imap/quota/i
mkdir -p ./DIR_var_imap/quota/u
mkdir -p ./DIR_var_imap/quota/d
mkdir -p ./DIR_var_imap/quota/n
mkdir -p ./DIR_var_imap/quota/k
mkdir -p ./DIR_var_imap/quota/o
mkdir -p ./DIR_var_imap/quota/s
mkdir -p ./DIR_var_imap/quota/h
mkdir -p ./DIR_var_imap/quota/j
mkdir -p ./DIR_var_imap/quota/g
mkdir -p ./DIR_var_imap/quota/r
mkdir -p ./DIR_var_imap/quota/p
mkdir -p ./DIR_var_imap/quota/v
mkdir -p ./DIR_var_imap/quota/y
mkdir -p ./DIR_var_imap/quota/t
mkdir -p ./DIR_var_imap/quota/m
mkdir -p ./DIR_var_imap/quota/f
mkdir -p ./DIR_var_imap/quota/l
mkdir -p ./DIR_var_imap/quota/a
mkdir -p ./DIR_var_imap/quota/w
mkdir -p ./DIR_var_imap/quota/b
mkdir -p ./DIR_var_imap/quota/e
mkdir -p ./DIR_var_imap/quota/c
mkdir -p ./DIR_var_imap/user
mkdir -p ./DIR_var_imap/user/z
mkdir -p ./DIR_var_imap/user/q
mkdir -p ./DIR_var_imap/user/x
mkdir -p ./DIR_var_imap/user/i
mkdir -p ./DIR_var_imap/user/u
mkdir -p ./DIR_var_imap/user/d
mkdir -p ./DIR_var_imap/user/n
mkdir -p ./DIR_var_imap/user/k
mkdir -p ./DIR_var_imap/user/o
mkdir -p ./DIR_var_imap/user/s
mkdir -p ./DIR_var_imap/user/h
mkdir -p ./DIR_var_imap/user/j
mkdir -p ./DIR_var_imap/user/g
mkdir -p ./DIR_var_imap/user/r
mkdir -p ./DIR_var_imap/user/p
mkdir -p ./DIR_var_imap/user/v
mkdir -p ./DIR_var_imap/user/y
mkdir -p ./DIR_var_imap/user/t
mkdir -p ./DIR_var_imap/user/m
mkdir -p ./DIR_var_imap/user/f
mkdir -p ./DIR_var_imap/user/l
mkdir -p ./DIR_var_imap/user/a
mkdir -p ./DIR_var_imap/user/w
mkdir -p ./DIR_var_imap/user/b
mkdir -p ./DIR_var_imap/user/e
mkdir -p ./DIR_var_imap/user/c
mkdir -p ./DIR_var_imap/msg
mkdir -p ./DIR_var_imap/log
mkdir -p ./DIR_var_imap/sieve
mkdir -p ./DIR_var_imap/sieve/z
mkdir -p ./DIR_var_imap/sieve/q
mkdir -p ./DIR_var_imap/sieve/x
mkdir -p ./DIR_var_imap/sieve/i
mkdir -p ./DIR_var_imap/sieve/u
mkdir -p ./DIR_var_imap/sieve/d
mkdir -p ./DIR_var_imap/sieve/n
mkdir -p ./DIR_var_imap/sieve/k
mkdir -p ./DIR_var_imap/sieve/o
mkdir -p ./DIR_var_imap/sieve/s
mkdir -p ./DIR_var_imap/sieve/h
mkdir -p ./DIR_var_imap/sieve/j
mkdir -p ./DIR_var_imap/sieve/g
mkdir -p ./DIR_var_imap/sieve/r
mkdir -p ./DIR_var_imap/sieve/p
mkdir -p ./DIR_var_imap/sieve/v
mkdir -p ./DIR_var_imap/sieve/y
mkdir -p ./DIR_var_imap/sieve/t
mkdir -p ./DIR_var_imap/sieve/m
mkdir -p ./DIR_var_imap/sieve/f
mkdir -p ./DIR_var_imap/sieve/l
mkdir -p ./DIR_var_imap/sieve/a
mkdir -p ./DIR_var_imap/sieve/w
mkdir -p ./DIR_var_imap/sieve/b
mkdir -p ./DIR_var_imap/sieve/e
mkdir -p ./DIR_var_imap/sieve/c
mkdir -p ./DIR_var_imap/socket
mkdir -p ./DIR_var_spool
mkdir -p ./DIR_var_spool/news
mkdir -p ./DIR_var_spool/imap
mkdir -p ./DIR_var_spool/imap/z
mkdir -p ./DIR_var_spool/imap/q
mkdir -p ./DIR_var_spool/imap/x
mkdir -p ./DIR_var_spool/imap/i
mkdir -p ./DIR_var_spool/imap/u
mkdir -p ./DIR_var_spool/imap/d
mkdir -p ./DIR_var_spool/imap/n
mkdir -p ./DIR_var_spool/imap/k
mkdir -p ./DIR_var_spool/imap/o
mkdir -p ./DIR_var_spool/imap/s
mkdir -p ./DIR_var_spool/imap/h
mkdir -p ./DIR_var_spool/imap/stage.
mkdir -p ./DIR_var_spool/imap/j
mkdir -p ./DIR_var_spool/imap/g
mkdir -p ./DIR_var_spool/imap/r
mkdir -p ./DIR_var_spool/imap/p
mkdir -p ./DIR_var_spool/imap/v
mkdir -p ./DIR_var_spool/imap/y
mkdir -p ./DIR_var_spool/imap/t
mkdir -p ./DIR_var_spool/imap/m
mkdir -p ./DIR_var_spool/imap/f
mkdir -p ./DIR_var_spool/imap/l
mkdir -p ./DIR_var_spool/imap/a
mkdir -p ./DIR_var_spool/imap/w
mkdir -p ./DIR_var_spool/imap/b
mkdir -p ./DIR_var_spool/imap/e
mkdir -p ./DIR_var_spool/imap/c
mkdir -p ./DIR_var_spool/cups
mkdir -p ./DIR_var_spool/cups/tmp
mkdir -p ./DIR_var_spool/clientmqueue
mkdir -p ./DIR_var_spool/uucp
mkdir -p ./DIR_var_spool/p3scan
mkdir -p ./DIR_var_spool/cron
mkdir -p ./DIR_var_spool/cron/crontabs
mkdir -p ./DIR_var_spool/cron/lastrun
mkdir -p ./DIR_var_cache
mkdir -p ./DIR_var_cache/localepurge
mkdir -p ./DIR_var_cache/genkernel
mkdir -p ./DIR_var_cache/man
mkdir -p ./DIR_var_cache/edb
mkdir -p ./DIR_var_cache/edb/dep
mkdir -p ./DIR_var_cache/edb/dep/usr
mkdir -p ./DIR_var_cache/edb/dep/usr/portage
mkdir -p ./DIR_var_cache/edb/dep/ports
mkdir -p ./DIR_var_cache/edb/dep/ports/portage
mkdir -p ./DIR_var_cache/edb/dep/ports/APPLIANCE
mkdir -p ./DIR_var_cache/edb/dep/ports/APPLIANCE/net-fs
mkdir -p ./DIR_var_cache/edb/dep/ports/APPLIANCE/dev-util
mkdir -p ./DIR_var_cache/edb/dep/var
mkdir -p ./DIR_var_cache/edb/dep/var/lib
mkdir -p ./DIR_var_cache/edb/dep/var/lib/layman
mkdir -p ./DIR_var_cache/edb/dep/var/lib/layman/dotnet
mkdir -p ./DIR_var_cache/edb/dep/var/lib/layman/dotnet/media-sound
mkdir -p ./DIR_var_cache/edb/dep/var/lib/layman/dotnet/games-board
mkdir -p ./DIR_var_cache/edb/dep/var/lib/layman/dotnet/app-emacs
mkdir -p ./DIR_var_cache/edb/dep/var/lib/layman/dotnet/net-irc
mkdir -p ./DIR_var_cache/edb/dep/var/lib/layman/dotnet/dev-lang
mkdir -p ./DIR_var_cache/edb/dep/var/lib/layman/dotnet/dev-dotnet
mkdir -p ./DIR_var_cache/edb/dep/var/lib/layman/dotnet/dev-util
mkdir -p ./DIR_var_cache/squid
mkdir -p ./DIR_var_cache/pear
mkdir -p ./DIR_var_cache/revdep-rebuild
mkdir -p ./DIR_var_cache/ldconfig
mkdir -p ./DIR_var_cache/eix
mkdir -p ./DIR_var_cache/fontconfig
mkdir -p ./DIR_var_cache/samba
mkdir -p ./DIR_var_lib
mkdir -p ./DIR_var_lib/ipmiutil
mkdir -p ./DIR_var_lib/bluetooth
mkdir -p ./DIR_var_lib/milter
mkdir -p ./DIR_var_lib/mysql
mkdir -p ./DIR_var_lib/dbus
mkdir -p ./DIR_var_lib/corosync
mkdir -p ./DIR_var_lib/csync2
mkdir -p ./DIR_var_lib/psad
mkdir -p ./DIR_var_lib/layman
mkdir -p ./DIR_var_lib/genkernel
mkdir -p ./DIR_var_lib/genkernel/src
mkdir -p ./DIR_var_lib/polkit-1
mkdir -p ./DIR_var_lib/argus
mkdir -p ./DIR_var_lib/dracut
mkdir -p ./DIR_var_lib/dracut/overlay
mkdir -p ./DIR_var_lib/portage
mkdir -p ./DIR_var_lib/openntpd
mkdir -p ./DIR_var_lib/openntpd/chroot
mkdir -p ./DIR_var_lib/openntpd/chroot/etc
mkdir -p ./DIR_var_lib/mlocate
mkdir -p ./DIR_var_lib/arpd
mkdir -p ./DIR_var_lib/net-snmp
mkdir -p ./DIR_var_lib/net-snmp/mib_indexes
mkdir -p ./DIR_var_lib/module-rebuild
mkdir -p ./DIR_var_lib/ntp
mkdir -p ./DIR_var_lib/nftables
mkdir -p ./DIR_var_lib/openldap-data
mkdir -p ./DIR_var_lib/iptraf-ng
mkdir -p ./DIR_var_lib/systemd
mkdir -p ./DIR_var_lib/systemd/rfkill
mkdir -p ./DIR_var_lib/systemd/catalog
mkdir -p ./DIR_var_lib/systemd/coredump
mkdir -p ./DIR_var_lib/plymouth
mkdir -p ./DIR_var_lib/rrdcached
mkdir -p ./DIR_var_lib/rrdcached/db
mkdir -p ./DIR_var_lib/rrdcached/journal
mkdir -p ./DIR_var_lib/syslog-ng
mkdir -p ./DIR_var_lib/netatalk
mkdir -p ./DIR_var_lib/netatalk/CNID
mkdir -p ./DIR_var_lib/squid
mkdir -p ./DIR_var_lib/lib
mkdir -p ./DIR_var_lib/lib/libdbi
mkdir -p ./DIR_var_lib/lib/libdbi/sqlite3
mkdir -p ./DIR_var_lib/lib/libdbi/firebird
mkdir -p ./DIR_var_lib/lib/libdbi/sqlite
mkdir -p ./DIR_var_lib/heartbeat
mkdir -p ./DIR_var_lib/heartbeat/cores
mkdir -p ./DIR_var_lib/heartbeat/cores/nobody
mkdir -p ./DIR_var_lib/heartbeat/cores/hacluster
mkdir -p ./DIR_var_lib/heartbeat/cores/root
mkdir -p ./DIR_var_lib/heartbeat/lrm
mkdir -p ./DIR_var_lib/spamassassin
mkdir -p ./DIR_var_lib/nginx
mkdir -p ./DIR_var_lib/nginx/tmp
mkdir -p ./DIR_var_lib/nginx/tmp/scgi
mkdir -p ./DIR_var_lib/nginx/tmp/client
mkdir -p ./DIR_var_lib/nginx/tmp/fastcgi
mkdir -p ./DIR_var_lib/nginx/tmp/uwsgi
mkdir -p ./DIR_var_lib/nginx/tmp/proxy
mkdir -p ./DIR_var_lib/rkhunter
mkdir -p ./DIR_var_lib/rkhunter/db
mkdir -p ./DIR_var_lib/rkhunter/db/i18n
mkdir -p ./DIR_var_lib/connman
mkdir -p ./DIR_var_lib/clamav
mkdir -p ./DIR_var_lib/racoon
mkdir -p ./DIR_var_lib/collectd
mkdir -p ./DIR_var_lib/pfl
mkdir -p ./DIR_var_lib/ip6tables
mkdir -p ./DIR_var_lib/entropy
mkdir -p ./DIR_var_lib/entropy/client
mkdir -p ./DIR_var_lib/entropy/client/packages
mkdir -p ./DIR_var_lib/samba
mkdir -p ./DIR_var_lib/samba/private
mkdir -p ./DIR_var_lib/dhcp
mkdir -p ./DIR_var_lib/rpm
mkdir -p ./DIR_var_lib/tripwire
mkdir -p ./DIR_var_lib/tripwire/report
mkdir -p ./DIR_var_lib/iptables
mkdir -p ./DIR_var_lib/ebtables
mkdir -p ./DIR_var_lib/fail2ban
mkdir -p ./DIR_var_lib/nfs
mkdir -p ./DIR_var_lib/nfs/sm.bak
mkdir -p ./DIR_var_lib/nfs/sm
mkdir -p ./DIR_var_lib/run
mkdir -p ./DIR_var_lib/run/radiusd
mkdir -p ./DIR_var_lib/misc
mkdir -p ./DIR_var_lib/NetworkManager
mkdir -p ./DIR_var_lib/libvirt
mkdir -p ./DIR_var_lib/libvirt/filesystems
mkdir -p ./DIR_var_lib/libvirt/network
mkdir -p ./DIR_var_lib/libvirt/dnsmasq
mkdir -p ./DIR_var_lib/libvirt/images
mkdir -p ./DIR_var_lib/libvirt/qemu
mkdir -p ./DIR_var_lib/libvirt/qemu/nvram
mkdir -p ./DIR_var_lib/libvirt/qemu/channel
mkdir -p ./DIR_var_lib/libvirt/qemu/channel/target
mkdir -p ./DIR_var_lib/libvirt/lockd
mkdir -p ./DIR_var_lib/libvirt/lockd/files
mkdir -p ./DIR_var_lib/libvirt/boot
mkdir -p ./DIR_var_lib/gentoo
mkdir -p ./DIR_var_lib/gentoo/news
mkdir -p ./DIR_var_tmp
mkdir -p ./DIR_var_tmp/systemd-private-85424382769343dc968969b56eaff043-systemd-timesyncd.service-6m2zmS
mkdir -p ./DIR_var_tmp/systemd-private-85424382769343dc968969b56eaff043-systemd-timesyncd.service-6m2zmS/tmp
mkdir -p ./DIR_var_www
mkdir -p ./DIR_var_www/localhost
mkdir -p ./DIR_var_empty
mkdir -p ./DIR_var_empty/dev
mkdir -p ./DIR_var_heimdal
mkdir -p ./DIR_var_target
mkdir -p ./DIR_var_target/fabric
mkdir -p ./DIR_var_bind
mkdir -p ./DIR_var_bind/dyn
mkdir -p ./DIR_var_bind/pri
mkdir -p ./DIR_var_bind/sec

